### ISSUE TITLE
Using tick instead of index in KartController

### ISSUE THREAD

**Issue by garyholiday** [adammyhre/Unity-Multiplayer-Kart#1]
On this line in the KartController: https://github.com/adammyhre/Unity-Multiplayer-Kart/blob/master/Assets/_Project/Scripts/KartController.cs#L354C13-L354C66 

It looks like you are using the rewindstate.tick but it should be a buffer index. I believe the line should read `clientStateBuffer.Add(rewindState, rewindState.tick % k_bufferSize);`

**Comment by adammyhre** [comment]
Looks like you are right, I'll fix that up tonight.  Thanks for reporting that issue!
