### ISSUE TITLE
ClientStateBuffer is 1 position further than ServerStateBuffer in HandleServerReconciliation() when you are the host.

### ISSUE THREAD

**Issue by garyholiday** [adammyhre/Unity-Multiplayer-Kart#2]
On these lines in https://github.com/adammyhre/Unity-Multiplayer-Kart/blob/master/Assets/_Project/Scripts/KartController.cs#L335-L336

If you are the host, you use the latest state in the server buffer, this makes sense because the host gets updated immediately. However, the execution order of these functions is as follows:
```
HandleClientTick()
HandleServerReconciliation()
HandleServerTick()
```

This means you update the `clientStateBuffer` with the latest client position, and it is 1 index further than the `serverStateBuffer`, so when you are the host, you grab the latest server state from `serverStateBuffer`, but its 1 index behind the `clientStateBuffer`. 

This most likely isn't an issue, because the reconciliation threshold should be within the allowable limit, but that may not always be true if you have a low threshold. 

I suggest doing something like this: 
```
rewindState = IsHost ? serverStateBuffer.Get(bufferIndex - 1) : lastServerState;
StatePayload clientStateAtTick = IsHost ? clientStateBuffer.Get(bufferIndex - 1) : clientStateBuffer.Get(bufferIndex);
```

This will make it so the host is comparing client states at the same ticks.

**Comment by adammyhre** [comment]
Thanks for the suggestion; that seems like a good improvement.  I will test it out tonight!  I appreciate the code review!
